package ru.bethel.domain.model

val oldTestament = listOf(
    BookHead("Ծննդ", (1..50).map { Chapter("Գլուխ $it", "", emptyList()) }),
    BookHead("Ել", (1..40).map { Chapter("Գլուխ $it", "", emptyList()) }),
    BookHead("Ղև", (1..27).map { Chapter("Գլուխ $it", "", emptyList()) }),
    BookHead("Թվ", (1..36).map { Chapter("Գլուխ $it", "", emptyList()) }),
    BookHead("2Օր", (1..34).map { Chapter("Գլուխ $it", "", emptyList()) }),
    BookHead("Հեսու", (1..24).map { Chapter("Գլուխ $it", "", emptyList()) }),
    BookHead("Դատ", (1..21).map { Chapter("Գլուխ $it", "", emptyList()) }),
    BookHead("Հռութ", (1..4).map { Chapter("Գլուխ $it", "", emptyList()) }),
    BookHead("1 Թագ", (1..31).map { Chapter("Գլուխ $it", "", emptyList()) }),
    BookHead("2 Թագ", (1..25).map { Chapter("Գլուխ $it", "", emptyList()) }),
    BookHead("3 Թագ", (1..22).map { Chapter("Գլուխ $it", "", emptyList()) }),
    BookHead("4 Թագ", (1..25).map { Chapter("Գլուխ $it", "", emptyList()) }),
    BookHead("1 Մնաց", (1..29).map { Chapter("Գլուխ $it", "", emptyList()) }),
    BookHead("2 Մնաց", (1..36).map { Chapter("Գլուխ $it", "", emptyList()) }),
    BookHead("Եզր", (1..10).map { Chapter("Գլուխ $it", "", emptyList()) }),
    BookHead("Նեեմ", (1..13).map { Chapter("Գլուխ $it", "", emptyList()) }),
    BookHead("Եսթ", (1..10).map { Chapter("Գլուխ $it", "", emptyList()) }),
    BookHead("Հոբ", (1..42).map { Chapter("Գլուխ $it", "", emptyList()) }),
    BookHead("Սաղ", (1..150).map { Chapter("Գլուխ $it", "", emptyList()) }),
    BookHead("Առ", (1..31).map { Chapter("Գլուխ $it", "", emptyList()) }),
    BookHead("Ժող", (1..12).map { Chapter("Գլուխ $it", "", emptyList()) }),
    BookHead("Երգ", (1..12).map { Chapter("Գլուխ $it", "", emptyList()) }),
    BookHead("Ես", (1..66).map { Chapter("Գլուխ $it", "", emptyList()) }),
    BookHead("Եր", (1..52).map { Chapter("Գլուխ $it", "", emptyList()) }),
    BookHead("Ողբ", (1..5).map { Chapter("Գլուխ $it", "", emptyList()) }),
    BookHead("Եզ", (1..48).map { Chapter("Գլուխ $it", "", emptyList()) }),
    BookHead("Դան", (1..12).map { Chapter("Գլուխ $it", "", emptyList()) }),
    BookHead("Ովս", (1..1).map { Chapter("Գլուխ $it", "", emptyList()) }),
    BookHead("Հովել", (1..3).map { Chapter("Գլուխ $it", "", emptyList()) }),
    BookHead("Ամո", (1..9).map { Chapter("Գլուխ $it", "", emptyList()) }),
    BookHead("Աբդ", (1..1).map { Chapter("Գլուխ $it", "", emptyList()) }),
    BookHead("Հովն", (1..4).map { Chapter("Գլուխ $it", "", emptyList()) }),
    BookHead("Միք", (1..7).map { Chapter("Գլուխ $it", "", emptyList()) }),
    BookHead("Նաում", (1..3).map { Chapter("Գլուխ $it", "", emptyList()) }),
    BookHead("Ամբ", (1..3).map { Chapter("Գլուխ $it", "", emptyList()) }),
    BookHead("Սոփ", (1..3).map { Chapter("Գլուխ $it", "", emptyList()) }),
    BookHead("Անգ", (1..2).map { Chapter("Գլուխ $it", "", emptyList()) }),
    BookHead("Զաք", (1..14).map { Chapter("Գլուխ $it", "", emptyList()) }),
    BookHead("Մաղ", (1..4).map { Chapter("Գլուխ $it", "", emptyList()) })
)

val newTestament = listOf(
    BookHead("Մատ", (1..28).map { Chapter("Գլուխ $it", "", emptyList()) }),
    BookHead("Մար", (1..16).map { Chapter("Գլուխ $it", "", emptyList()) }),
    BookHead("Ղուկ", (1..24).map { Chapter("Գլուխ $it", "", emptyList()) }),
    BookHead("Հովհ", (1..21).map { Chapter("Գլուխ $it", "", emptyList()) }),
    BookHead("Գործ", (1..28).map { Chapter("Գլուխ $it", "", emptyList()) }),
    BookHead("Հռ", (1..16).map { Chapter("Գլուխ $it", "", emptyList()) }),
    BookHead("1 Կոր", (1..16).map { Chapter("Գլուխ $it", "", emptyList()) }),
    BookHead("2 Կոր", (1..13).map { Chapter("Գլուխ $it", "", emptyList()) }),
    BookHead("Գաղ", (1..6).map { Chapter("Գլուխ $it", "", emptyList()) }),
    BookHead("Եփ", (1..6).map { Chapter("Գլուխ $it", "", emptyList()) }),
    BookHead("Փիլիպ", (1..4).map { Chapter("Գլուխ $it", "", emptyList()) }),
    BookHead("Կող", (1..4).map { Chapter("Գլուխ $it", "", emptyList()) }),
    BookHead("1 Թես", (1..5).map { Chapter("Գլուխ $it", "", emptyList()) }),
    BookHead("2Թես", (1..3).map { Chapter("Գլուխ $it", "", emptyList()) }),
    BookHead("1 Տիմ", (1..6).map { Chapter("Գլուխ $it", "", emptyList()) }),
    BookHead("2 Տիմ", (1..4).map { Chapter("Գլուխ $it", "", emptyList()) }),
    BookHead("Տիտ", (1..3).map { Chapter("Գլուխ $it", "", emptyList()) }),
    BookHead("Փիլիմ", (1..1).map { Chapter("Գլուխ $it", "", emptyList()) }),
    BookHead("Եբր", (1..13).map { Chapter("Գլուխ $it", "", emptyList()) }),
    BookHead("Հակ", (1..5).map { Chapter("Գլուխ $it", "", emptyList()) }),
    BookHead("1 Պետ", (1..5).map { Chapter("Գլուխ $it", "", emptyList()) }),
    BookHead("2 Պետ", (1..3).map { Chapter("Գլուխ $it", "", emptyList()) }),
    BookHead("1 Հով", (1..5).map { Chapter("Գլուխ $it", "", emptyList()) }),
    BookHead("2 Հով", (1..1).map { Chapter("Գլուխ $it", "", emptyList()) }),
    BookHead("3 Հով", (1..1).map { Chapter("Գլուխ $it", "", emptyList()) }),
    BookHead("Հուդա", (1..1).map { Chapter("Գլուխ $it", "", emptyList()) }),
    BookHead("Հայ", (1..22).map { Chapter("Գլուխ $it", "", emptyList()) })
)
