package ru.bethel.domain.model

private val basicSubTitleList :  List<SubTitle> = listOf(
    SubTitle(title = "Սկիզբ" , "00:00 - 01։12"),
    SubTitle(title = "Մեջտեղ" , "01։12 - 02.48"),
    SubTitle(title = "Վերջ" , "02.48 - 05.12"),
)


val oldTestament = listOf(
    BookHead("Ծննդ", (1..50).map { Chapter("Գլուխ $it", "https://www.derekprincearmenia.com/audiofiles/hy/1/$it.mp3", basicSubTitleList) }),
    BookHead("Ել", (1..40).map { Chapter("Գլուխ $it", "https://www.derekprincearmenia.com/audiofiles/hy/2/$it.mp3", basicSubTitleList) }),
    BookHead("Ղև", (1..27).map { Chapter("Գլուխ $it", "https://www.derekprincearmenia.com/audiofiles/hy/3/$it.mp3", basicSubTitleList) }),
    BookHead("Թվ", (1..36).map { Chapter("Գլուխ $it", "https://www.derekprincearmenia.com/audiofiles/hy/4/$it.mp3", basicSubTitleList) }),
    BookHead("2Օր", (1..34).map { Chapter("Գլուխ $it", "https://www.derekprincearmenia.com/audiofiles/hy/5/$it.mp3", basicSubTitleList) }),
    BookHead("Հեսու", (1..24).map { Chapter("Գլուխ $it", "https://www.derekprincearmenia.com/audiofiles/hy/6/$it.mp3", basicSubTitleList) }),
    BookHead("Դատ", (1..21).map { Chapter("Գլուխ $it", "https://www.derekprincearmenia.com/audiofiles/hy/7/$it.mp3", basicSubTitleList) }),
    BookHead("Հռութ", (1..4).map { Chapter("Գլուխ $it", "https://www.derekprincearmenia.com/audiofiles/hy/8/$it.mp3", basicSubTitleList) }),
    BookHead("1 Թագ", (1..31).map { Chapter("Գլուխ $it", "https://www.derekprincearmenia.com/audiofiles/hy/9/$it.mp3", basicSubTitleList) }),
    BookHead("2 Թագ", (1..25).map { Chapter("Գլուխ $it", "https://www.derekprincearmenia.com/audiofiles/hy/10/$it.mp3", basicSubTitleList) }),
    BookHead("3 Թագ", (1..22).map { Chapter("Գլուխ $it", "https://www.derekprincearmenia.com/audiofiles/hy/11/$it.mp3", basicSubTitleList) }),
    BookHead("4 Թագ", (1..25).map { Chapter("Գլուխ $it", "https://www.derekprincearmenia.com/audiofiles/hy/12/$it.mp3", basicSubTitleList) }),
    BookHead("1 Մնաց", (1..29).map { Chapter("Գլուխ $it", "https://www.derekprincearmenia.com/audiofiles/hy/13/$it.mp3", basicSubTitleList) }),
    BookHead("2 Մնաց", (1..36).map { Chapter("Գլուխ $it", "https://www.derekprincearmenia.com/audiofiles/hy/14/$it.mp3", basicSubTitleList) }),
    BookHead("Եզր", (1..10).map { Chapter("Գլուխ $it", "https://www.derekprincearmenia.com/audiofiles/hy/15/$it.mp3", basicSubTitleList) }),
    BookHead("Նեեմ", (1..13).map { Chapter("Գլուխ $it", "https://www.derekprincearmenia.com/audiofiles/hy/16/$it.mp3", basicSubTitleList) }),
    BookHead("Եսթ", (1..10).map { Chapter("Գլուխ $it", "https://www.derekprincearmenia.com/audiofiles/hy/17/$it.mp3", basicSubTitleList) }),
    BookHead("Հոբ", (1..42).map { Chapter("Գլուխ $it", "https://www.derekprincearmenia.com/audiofiles/hy/18/$it.mp3", basicSubTitleList) }),
    BookHead("Սաղ", (1..150).map { Chapter("Գլուխ $it", "https://www.derekprincearmenia.com/audiofiles/hy/19/$it.mp3", basicSubTitleList) }),
    BookHead("Առ", (1..31).map { Chapter("Գլուխ $it", "https://www.derekprincearmenia.com/audiofiles/hy/19/$it.mp3", basicSubTitleList) }),
    BookHead("Ժող", (1..12).map { Chapter("Գլուխ $it", "https://www.derekprincearmenia.com/audiofiles/hy/21/$it.mp3", basicSubTitleList) }),
    BookHead("Երգ", (1..12).map { Chapter("Գլուխ $it", "https://www.derekprincearmenia.com/audiofiles/hy/22/$it.mp3", basicSubTitleList) }),
    BookHead("Ես", (1..66).map { Chapter("Գլուխ $it", "https://www.derekprincearmenia.com/audiofiles/hy/23/$it.mp3", basicSubTitleList) }),
    BookHead("Եր", (1..52).map { Chapter("Գլուխ $it", "https://www.derekprincearmenia.com/audiofiles/hy/24/$it.mp3", basicSubTitleList) }),
    BookHead("Ողբ", (1..5).map { Chapter("Գլուխ $it", "https://www.derekprincearmenia.com/audiofiles/hy/25/$it.mp3", basicSubTitleList) }),
    BookHead("Եզ", (1..48).map { Chapter("Գլուխ $it", "https://www.derekprincearmenia.com/audiofiles/hy/26/$it.mp3", basicSubTitleList) }),
    BookHead("Դան", (1..12).map { Chapter("Գլուխ $it", "https://www.derekprincearmenia.com/audiofiles/hy/27/$it.mp3", basicSubTitleList) }),
    BookHead("Ովս", (1..1).map { Chapter("Գլուխ $it", "https://www.derekprincearmenia.com/audiofiles/hy/28/$it.mp3", basicSubTitleList) }),
    BookHead("Հովել", (1..3).map { Chapter("Գլուխ $it", "https://www.derekprincearmenia.com/audiofiles/hy/29/$it.mp3", basicSubTitleList) }),
    BookHead("Ամո", (1..9).map { Chapter("Գլուխ $it", "https://www.derekprincearmenia.com/audiofiles/hy/30/$it.mp3", basicSubTitleList) }),
    BookHead("Աբդ", (1..1).map { Chapter("Գլուխ $it", "https://www.derekprincearmenia.com/audiofiles/hy/31/$it.mp3", basicSubTitleList) }),
    BookHead("Հովն", (1..4).map { Chapter("Գլուխ $it", "https://www.derekprincearmenia.com/audiofiles/hy/32/$it.mp3", basicSubTitleList) }),
    BookHead("Միք", (1..7).map { Chapter("Գլուխ $it", "https://www.derekprincearmenia.com/audiofiles/hy/33/$it.mp3", basicSubTitleList) }),
    BookHead("Նաում", (1..3).map { Chapter("Գլուխ $it", "https://www.derekprincearmenia.com/audiofiles/hy/34/$it.mp3", basicSubTitleList) }),
    BookHead("Ամբ", (1..3).map { Chapter("Գլուխ $it", "https://www.derekprincearmenia.com/audiofiles/hy/35/$it.mp3", basicSubTitleList) }),
    BookHead("Սոփ", (1..3).map { Chapter("Գլուխ $it", "https://www.derekprincearmenia.com/audiofiles/hy/36/$it.mp3", basicSubTitleList) }),
    BookHead("Անգ", (1..2).map { Chapter("Գլուխ $it", "https://www.derekprincearmenia.com/audiofiles/hy/37/$it.mp3", basicSubTitleList) }),
    BookHead("Զաք", (1..14).map { Chapter("Գլուխ $it", "https://www.derekprincearmenia.com/audiofiles/hy/38/$it.mp3", basicSubTitleList) }),
    BookHead("Մաղ", (1..4).map { Chapter("Գլուխ $it", "https://www.derekprincearmenia.com/audiofiles/hy/39/$it.mp3", basicSubTitleList) })
)

val newTestament = listOf(
    BookHead("Մատ", (1..28).map { Chapter("Գլուխ $it", "https://www.derekprincearmenia.com/audiofiles/hy/40/$it.mp3", basicSubTitleList) }),
    BookHead("Մար", (1..16).map { Chapter("Գլուխ $it", "https://www.derekprincearmenia.com/audiofiles/hy/41/$it.mp3", basicSubTitleList) }),
    BookHead("Ղուկ", (1..24).map { Chapter("Գլուխ $it", "https://www.derekprincearmenia.com/audiofiles/hy/42/$it.mp3", basicSubTitleList) }),
    BookHead("Հովհ", (1..21).map { Chapter("Գլուխ $it", "https://www.derekprincearmenia.com/audiofiles/hy/43/$it.mp3", basicSubTitleList) }),
    BookHead("Գործ", (1..28).map { Chapter("Գլուխ $it", "https://www.derekprincearmenia.com/audiofiles/hy/44/$it.mp3", basicSubTitleList) }),
    BookHead("Հռ", (1..16).map { Chapter("Գլուխ $it", "https://www.derekprincearmenia.com/audiofiles/hy/45/$it.mp3", basicSubTitleList) }),
    BookHead("1 Կոր", (1..16).map { Chapter("Գլուխ $it", "https://www.derekprincearmenia.com/audiofiles/hy/46/$it.mp3", basicSubTitleList) }),
    BookHead("2 Կոր", (1..13).map { Chapter("Գլուխ $it", "https://www.derekprincearmenia.com/audiofiles/hy/47/$it.mp3", basicSubTitleList) }),
    BookHead("Գաղ", (1..6).map { Chapter("Գլուխ $it", "https://www.derekprincearmenia.com/audiofiles/hy/48/$it.mp3", basicSubTitleList) }),
    BookHead("Եփ", (1..6).map { Chapter("Գլուխ $it", "https://www.derekprincearmenia.com/audiofiles/hy/49/$it.mp3", basicSubTitleList) }),
    BookHead("Փիլիպ", (1..4).map { Chapter("Գլուխ $it", "https://www.derekprincearmenia.com/audiofiles/hy/50/$it.mp3", basicSubTitleList) }),
    BookHead("Կող", (1..4).map { Chapter("Գլուխ $it", "https://www.derekprincearmenia.com/audiofiles/hy/51/$it.mp3", basicSubTitleList) }),
    BookHead("1 Թես", (1..5).map { Chapter("Գլուխ $it", "https://www.derekprincearmenia.com/audiofiles/hy/52/$it.mp3", basicSubTitleList) }),
    BookHead("2Թես", (1..3).map { Chapter("Գլուխ $it", "https://www.derekprincearmenia.com/audiofiles/hy/53/$it.mp3", basicSubTitleList) }),
    BookHead("1 Տիմ", (1..6).map { Chapter("Գլուխ $it", "https://www.derekprincearmenia.com/audiofiles/hy/54/$it.mp3", basicSubTitleList) }),
    BookHead("2 Տիմ", (1..4).map { Chapter("Գլուխ $it", "https://www.derekprincearmenia.com/audiofiles/hy/55/$it.mp3", basicSubTitleList) }),
    BookHead("Տիտ", (1..3).map { Chapter("Գլուխ $it", "https://www.derekprincearmenia.com/audiofiles/hy/56/$it.mp3", basicSubTitleList) }),
    BookHead("Փիլիմ", (1..1).map { Chapter("Գլուխ $it", "https://www.derekprincearmenia.com/audiofiles/hy/57/$it.mp3", basicSubTitleList) }),
    BookHead("Եբր", (1..13).map { Chapter("Գլուխ $it", "https://www.derekprincearmenia.com/audiofiles/hy/58/$it.mp3", basicSubTitleList) }),
    BookHead("Հակ", (1..5).map { Chapter("Գլուխ $it", "https://www.derekprincearmenia.com/audiofiles/hy/59/$it.mp3", basicSubTitleList) }),
    BookHead("1 Պետ", (1..5).map { Chapter("Գլուխ $it", "https://www.derekprincearmenia.com/audiofiles/hy/60/$it.mp3", basicSubTitleList) }),
    BookHead("2 Պետ", (1..3).map { Chapter("Գլուխ $it", "https://www.derekprincearmenia.com/audiofiles/hy/61/$it.mp3", basicSubTitleList) }),
    BookHead("1 Հով", (1..5).map { Chapter("Գլուխ $it", "https://www.derekprincearmenia.com/audiofiles/hy/62/$it.mp3", basicSubTitleList) }),
    BookHead("2 Հով", (1..1).map { Chapter("Գլուխ $it", "https://www.derekprincearmenia.com/audiofiles/hy/63/$it.mp3", basicSubTitleList) }),
    BookHead("3 Հով", (1..1).map { Chapter("Գլուխ $it", "https://www.derekprincearmenia.com/audiofiles/hy/64/$it.mp3", basicSubTitleList) }),
    BookHead("Հուդա", (1..1).map { Chapter("Գլուխ $it", "https://www.derekprincearmenia.com/audiofiles/hy/65/$it.mp3", basicSubTitleList) }),
    BookHead("Հայ", (1..22).map { Chapter("Գլուխ $it", "https://www.derekprincearmenia.com/audiofiles/hy/66/$it.mp3", basicSubTitleList) })
)
