package ru.bethel.domain.model

val oldTestament = listOf(
    BookHead("Ծննդ", (1..50).map { Chapter("Գլուխ $it", "https://www.derekprincearmenia.com/audiofiles/hy/1/$it.mp3", emptyList()) }),
    BookHead("Ել", (1..40).map { Chapter("Գլուխ $it", "https://www.derekprincearmenia.com/audiofiles/hy/2/$it.mp3", emptyList()) }),
    BookHead("Ղև", (1..27).map { Chapter("Գլուխ $it", "https://www.derekprincearmenia.com/audiofiles/hy/3/$it.mp3", emptyList()) }),
    BookHead("Թվ", (1..36).map { Chapter("Գլուխ $it", "https://www.derekprincearmenia.com/audiofiles/hy/4/$it.mp3", emptyList()) }),
    BookHead("2Օր", (1..34).map { Chapter("Գլուխ $it", "https://www.derekprincearmenia.com/audiofiles/hy/5/$it.mp3", emptyList()) }),
    BookHead("Հեսու", (1..24).map { Chapter("Գլուխ $it", "https://www.derekprincearmenia.com/audiofiles/hy/6/$it", emptyList()) }),
    BookHead("Դատ", (1..21).map { Chapter("Գլուխ $it", "https://www.derekprincearmenia.com/audiofiles/hy/7/$it", emptyList()) }),
    BookHead("Հռութ", (1..4).map { Chapter("Գլուխ $it", "https://www.derekprincearmenia.com/audiofiles/hy/8/$it", emptyList()) }),
    BookHead("1 Թագ", (1..31).map { Chapter("Գլուխ $it", "https://www.derekprincearmenia.com/audiofiles/hy/9/$it", emptyList()) }),
    BookHead("2 Թագ", (1..25).map { Chapter("Գլուխ $it", "https://www.derekprincearmenia.com/audiofiles/hy/10/$it", emptyList()) }),
    BookHead("3 Թագ", (1..22).map { Chapter("Գլուխ $it", "https://www.derekprincearmenia.com/audiofiles/hy/11/$it", emptyList()) }),
    BookHead("4 Թագ", (1..25).map { Chapter("Գլուխ $it", "https://www.derekprincearmenia.com/audiofiles/hy/12/$it", emptyList()) }),
    BookHead("1 Մնաց", (1..29).map { Chapter("Գլուխ $it", "https://www.derekprincearmenia.com/audiofiles/hy/13/$it", emptyList()) }),
    BookHead("2 Մնաց", (1..36).map { Chapter("Գլուխ $it", "https://www.derekprincearmenia.com/audiofiles/hy/14/$it", emptyList()) }),
    BookHead("Եզր", (1..10).map { Chapter("Գլուխ $it", "https://www.derekprincearmenia.com/audiofiles/hy/15/$it", emptyList()) }),
    BookHead("Նեեմ", (1..13).map { Chapter("Գլուխ $it", "https://www.derekprincearmenia.com/audiofiles/hy/16/$it", emptyList()) }),
    BookHead("Եսթ", (1..10).map { Chapter("Գլուխ $it", "https://www.derekprincearmenia.com/audiofiles/hy/17/$it", emptyList()) }),
    BookHead("Հոբ", (1..42).map { Chapter("Գլուխ $it", "https://www.derekprincearmenia.com/audiofiles/hy/18/$it", emptyList()) }),
    BookHead("Սաղ", (1..150).map { Chapter("Գլուխ $it", "https://www.derekprincearmenia.com/audiofiles/hy/19/$it", emptyList()) }),
    BookHead("Առ", (1..31).map { Chapter("Գլուխ $it", "https://www.derekprincearmenia.com/audiofiles/hy/19/$it", emptyList()) }),
    BookHead("Ժող", (1..12).map { Chapter("Գլուխ $it", "https://www.derekprincearmenia.com/audiofiles/hy/21/$it", emptyList()) }),
    BookHead("Երգ", (1..12).map { Chapter("Գլուխ $it", "https://www.derekprincearmenia.com/audiofiles/hy/22/$it", emptyList()) }),
    BookHead("Ես", (1..66).map { Chapter("Գլուխ $it", "https://www.derekprincearmenia.com/audiofiles/hy/23/$it", emptyList()) }),
    BookHead("Եր", (1..52).map { Chapter("Գլուխ $it", "https://www.derekprincearmenia.com/audiofiles/hy/24/$it", emptyList()) }),
    BookHead("Ողբ", (1..5).map { Chapter("Գլուխ $it", "https://www.derekprincearmenia.com/audiofiles/hy/25/$it", emptyList()) }),
    BookHead("Եզ", (1..48).map { Chapter("Գլուխ $it", "https://www.derekprincearmenia.com/audiofiles/hy/26/$it", emptyList()) }),
    BookHead("Դան", (1..12).map { Chapter("Գլուխ $it", "https://www.derekprincearmenia.com/audiofiles/hy/27/$it", emptyList()) }),
    BookHead("Ովս", (1..1).map { Chapter("Գլուխ $it", "https://www.derekprincearmenia.com/audiofiles/hy/28/$it", emptyList()) }),
    BookHead("Հովել", (1..3).map { Chapter("Գլուխ $it", "https://www.derekprincearmenia.com/audiofiles/hy/29/$it", emptyList()) }),
    BookHead("Ամո", (1..9).map { Chapter("Գլուխ $it", "https://www.derekprincearmenia.com/audiofiles/hy/30/$it", emptyList()) }),
    BookHead("Աբդ", (1..1).map { Chapter("Գլուխ $it", "https://www.derekprincearmenia.com/audiofiles/hy/31/$it", emptyList()) }),
    BookHead("Հովն", (1..4).map { Chapter("Գլուխ $it", "https://www.derekprincearmenia.com/audiofiles/hy/32/$it", emptyList()) }),
    BookHead("Միք", (1..7).map { Chapter("Գլուխ $it", "https://www.derekprincearmenia.com/audiofiles/hy/33/$it", emptyList()) }),
    BookHead("Նաում", (1..3).map { Chapter("Գլուխ $it", "https://www.derekprincearmenia.com/audiofiles/hy/34/$it", emptyList()) }),
    BookHead("Ամբ", (1..3).map { Chapter("Գլուխ $it", "https://www.derekprincearmenia.com/audiofiles/hy/35/$it", emptyList()) }),
    BookHead("Սոփ", (1..3).map { Chapter("Գլուխ $it", "https://www.derekprincearmenia.com/audiofiles/hy/36/$it", emptyList()) }),
    BookHead("Անգ", (1..2).map { Chapter("Գլուխ $it", "https://www.derekprincearmenia.com/audiofiles/hy/37/$it", emptyList()) }),
    BookHead("Զաք", (1..14).map { Chapter("Գլուխ $it", "https://www.derekprincearmenia.com/audiofiles/hy/38/$it", emptyList()) }),
    BookHead("Մաղ", (1..4).map { Chapter("Գլուխ $it", "https://www.derekprincearmenia.com/audiofiles/hy/39/$it", emptyList()) })
)

val newTestament = listOf(
    BookHead("Մատ", (1..28).map { Chapter("Գլուխ $it", "https://www.derekprincearmenia.com/audiofiles/hy/40/$it", emptyList()) }),
    BookHead("Մար", (1..16).map { Chapter("Գլուխ $it", "https://www.derekprincearmenia.com/audiofiles/hy/41/$it", emptyList()) }),
    BookHead("Ղուկ", (1..24).map { Chapter("Գլուխ $it", "https://www.derekprincearmenia.com/audiofiles/hy/42/$it", emptyList()) }),
    BookHead("Հովհ", (1..21).map { Chapter("Գլուխ $it", "https://www.derekprincearmenia.com/audiofiles/hy/43/$it", emptyList()) }),
    BookHead("Գործ", (1..28).map { Chapter("Գլուխ $it", "https://www.derekprincearmenia.com/audiofiles/hy/44/$it", emptyList()) }),
    BookHead("Հռ", (1..16).map { Chapter("Գլուխ $it", "https://www.derekprincearmenia.com/audiofiles/hy/45/$it", emptyList()) }),
    BookHead("1 Կոր", (1..16).map { Chapter("Գլուխ $it", "https://www.derekprincearmenia.com/audiofiles/hy/46/$it", emptyList()) }),
    BookHead("2 Կոր", (1..13).map { Chapter("Գլուխ $it", "https://www.derekprincearmenia.com/audiofiles/hy/47/$it", emptyList()) }),
    BookHead("Գաղ", (1..6).map { Chapter("Գլուխ $it", "https://www.derekprincearmenia.com/audiofiles/hy/48/$it", emptyList()) }),
    BookHead("Եփ", (1..6).map { Chapter("Գլուխ $it", "https://www.derekprincearmenia.com/audiofiles/hy/49/$it", emptyList()) }),
    BookHead("Փիլիպ", (1..4).map { Chapter("Գլուխ $it", "https://www.derekprincearmenia.com/audiofiles/hy/50/$it", emptyList()) }),
    BookHead("Կող", (1..4).map { Chapter("Գլուխ $it", "https://www.derekprincearmenia.com/audiofiles/hy/51/$it", emptyList()) }),
    BookHead("1 Թես", (1..5).map { Chapter("Գլուխ $it", "https://www.derekprincearmenia.com/audiofiles/hy/52/$it", emptyList()) }),
    BookHead("2Թես", (1..3).map { Chapter("Գլուխ $it", "https://www.derekprincearmenia.com/audiofiles/hy/53/$it", emptyList()) }),
    BookHead("1 Տիմ", (1..6).map { Chapter("Գլուխ $it", "https://www.derekprincearmenia.com/audiofiles/hy/54/$it", emptyList()) }),
    BookHead("2 Տիմ", (1..4).map { Chapter("Գլուխ $it", "https://www.derekprincearmenia.com/audiofiles/hy/55/$it", emptyList()) }),
    BookHead("Տիտ", (1..3).map { Chapter("Գլուխ $it", "https://www.derekprincearmenia.com/audiofiles/hy/56/$it", emptyList()) }),
    BookHead("Փիլիմ", (1..1).map { Chapter("Գլուխ $it", "https://www.derekprincearmenia.com/audiofiles/hy/57/$it", emptyList()) }),
    BookHead("Եբր", (1..13).map { Chapter("Գլուխ $it", "https://www.derekprincearmenia.com/audiofiles/hy/58/$it", emptyList()) }),
    BookHead("Հակ", (1..5).map { Chapter("Գլուխ $it", "https://www.derekprincearmenia.com/audiofiles/hy/59/$it", emptyList()) }),
    BookHead("1 Պետ", (1..5).map { Chapter("Գլուխ $it", "https://www.derekprincearmenia.com/audiofiles/hy/60/$it", emptyList()) }),
    BookHead("2 Պետ", (1..3).map { Chapter("Գլուխ $it", "https://www.derekprincearmenia.com/audiofiles/hy/61/$it", emptyList()) }),
    BookHead("1 Հով", (1..5).map { Chapter("Գլուխ $it", "https://www.derekprincearmenia.com/audiofiles/hy/62/$it", emptyList()) }),
    BookHead("2 Հով", (1..1).map { Chapter("Գլուխ $it", "https://www.derekprincearmenia.com/audiofiles/hy/63/$it", emptyList()) }),
    BookHead("3 Հով", (1..1).map { Chapter("Գլուխ $it", "https://www.derekprincearmenia.com/audiofiles/hy/64/$it", emptyList()) }),
    BookHead("Հուդա", (1..1).map { Chapter("Գլուխ $it", "https://www.derekprincearmenia.com/audiofiles/hy/65/$it", emptyList()) }),
    BookHead("Հայ", (1..22).map { Chapter("Գլուխ $it", "https://www.derekprincearmenia.com/audiofiles/hy/66/$it", emptyList()) })
)
